# -*- coding: utf-8 -*-
"""Constants
"""

from ..config_local import PATH_DATA


#
### DATASET: raw
#

PATH_DATA_RAW = PATH_DATA+'/raw'


#
### DATASET: features02
#

FEATURES02_EYES_SIZE = (32,24)  # Eye img shape

# features02_dlib
PATH_DATA_FEATURES02_DLIB = PATH_DATA+"/features02_dlib/"
PATH_DATA_FEATURES02_DLIB_CSV = PATH_DATA_FEATURES02_DLIB+"features.csv"

# features02_dlib_augmented
PATH_DATA_FEATURES02_DLIB_AUGMENTED = PATH_DATA+"/features02_dlib_augmented/"
PATH_DATA_FEATURES02_DLIB_AUGMENTED_CSV = PATH_DATA_FEATURES02_DLIB_AUGMENTED+"features.csv"

# features02_dlib_augmented and normalized
PATH_DATA_FEATURES02_DLIB_AUGMENTED_NORM = PATH_DATA+"/features02_dlib_augmented_norm/"
PATH_DATA_FEATURES02_DLIB_AUGMENTED_NORM_CSV = PATH_DATA_FEATURES02_DLIB_AUGMENTED_NORM+"features.csv"
PATH_DATA_FEATURES02_DLIB_AUGMENTED_NORM_IMGS_LEFT = PATH_DATA_FEATURES02_DLIB_AUGMENTED_NORM+"img_left_norm"
PATH_DATA_FEATURES02_DLIB_AUGMENTED_NORM_IMGS_RIGHT = PATH_DATA_FEATURES02_DLIB_AUGMENTED_NORM+"img_right_norm"
